repos:
  - repo: local
    hooks:
      - id: detect-secrets
        name: detect-secrets
        entry: poetry run detect-secrets-hook
        language: system
        pass_filenames: true
        args:
          - --baseline
          - .secrets.baseline